#!/usr/bin/env bash

# Make sure this script is being run from the project root
if [[ ! -f 'cmd/clean' ]] ; then
    echo 'Can only be run from the project root directory.'
    exit 1
fi

# Select files to delete
files=('node_modules' 'bun.lock' 'package.json' 'site')

# Delete corresponding files
for file in "${files[@]}" ; do
    echo "Deleting ${file}..."
    find . -name "${file}" -prune -exec rm -rf {} +
done
