#!/usr/bin/env bash

# Check if building in dev mode or prod mode
if [[ "${1}" == 'dev' ]] ; then
    args=('--watch')
elif [[ "${1}" == 'prod' ]] ; then
    args=('--minify' '--format=iife')
else
    echo "Unknown argument ${1}."
    exit 1
fi

# Create project output directory
name="../../../site/$(basename "${PWD}")"
mkdir -p "${name}"

# Lint and build project
bun x tsc --noEmit && bun x eslint src && bun build "${args[@]}" --compile --target=browser ./index.html --outfile="${name}/index.html"
