#!/usr/bin/env bash

# Make sure this script is being run from the project root
if [[ ! -f '.github/workflows/clean' ]] ; then
    echo 'Can only be run from the project root directory.'
    exit 1
fi

# Check to make sure a single argument was provided
if [[ "${#}" -ne 1 ]] ; then
    echo "Usage: ${0} <dev|prod>"
    exit 1
fi

# Select files to delete
if [[ "${1}" == 'dev' ]] ; then
    files=('node_modules' 'dist' 'bun.lock')
elif [[ "${1}" == 'prod' ]] ; then
    files=('src' 'package.json' '*.md')
else
    echo "Unknown argument ${1}."
fi

# Delete corresponding files
for file in "${files[@]}" ; do
    echo "Deleting ${file}..."
    find . -name "${file}" -prune -exec rm -rf {} +
done
