#!/usr/bin/env bash

# Make sure this script is being run from the project root
if [[ ! -f '.github/workflows/clean' ]] ; then
    echo 'Can only be run from the project root directory.'
    exit 1
fi

# Check to make sure a single argument was provided
if [[ "${#}" -ne 1 ]] ; then
    echo "Usage: ${0} <dev|prod>"
    exit 1
fi

if [ "${1}" = 'dev' ] ; then
    rm -rf node_modules bun.lock
elif [ "${1}" = 'prod' ] ; then
    echo cleaning in prod mode
else
    echo "Unknown argument ${1}."
fi
